# 通用设置
title: Lygone's blog
name: "Lygone's Blog"
description: Everything about Lygone.
author_info: <a href="https://lygone.netlify.app/">Lygone</a>

# 核心 URL 配置
url: "https://lygone.netlify.app"

# 路径设置
permalink: /:title

# Markdown 和代码高亮
markdown: kramdown
highlighter: rouge

# RSS 订阅
feed: /atom.xml

# 其他
auto: true
